apiVersion: v1
kind: Pod  
metadata:  
  name: szymon
spec:      
  containers:
  - name: frontend
    image: registry.redhat.io/rhel8/httpd-24:latest
    #image: quay.io/redhattraining/httpd-parent
    ports: 
    - containerPort: 8080
           
  - name: backend
    image: registry.redhat.io/rhel8/mysql-80
    ports: 
    - containerPort: 3306
    env:   
    - name: MYSQL_USER
      valueFrom:
        configMapKeyRef:
          name: my-cm
          key: user
    - name: MYSQL_DATABASE
      valueFrom:
        configMapKeyRef:
          name: my-cm
          key: database
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: harry-redhat
          key: password
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: harry-redhat
          key: root_password
